### ISSUE TITLE
AttributeError: 'Projection' object has no attribute '_eye'

### ISSUE THREAD

**Issue by zhenhao-huang** [Jittor/unsup3d-jittor#1]
Traceback (most recent call last):
      File "run.py", line 24, in <module>
        trainer.train()
      File "/home/klein/Desktop/unsup3d-jittor/unsup3d/trainer.py", line 123, in train
        metrics = self.run_epoch(self.train_loader, epoch)
      File "/home/klein/Desktop/unsup3d-jittor/unsup3d/trainer.py", line 150, in run_epoch
        m = self.model.forward(input)
      File "/home/klein/Desktop/unsup3d-jittor/unsup3d/model.py", line 132, in forward
        self.recon_depth = self.renderer.warp_canon_depth(self.canon_depth)
      File "/home/klein/Desktop/unsup3d-jittor/unsup3d/renderer/renderer.py", line 112, in warp_canon_depth
        warped_depth = self.renderer(grid_3d, faces, mode='depth')
      File "/home/klein/anaconda3/envs/py37/lib/python3.7/site-packages/jittor/__init__.py", line 737, in __call__
        return self.execute(*args, **kw)
      File "/home/klein/Desktop/unsup3d-jittor/jrender/renderer/renderer.py", line 71, in execute
        return self.render_mesh(mesh, mode)
      File "/home/klein/Desktop/unsup3d-jittor/jrender/renderer/renderer.py", line 65, in render_mesh
        mesh = self.lighting(mesh, self.transform.eyes)
      File "/home/klein/Desktop/unsup3d-jittor/jrender/renderer/transform/transform.py", line 111, in eyes
        return self.transformer._eye

**Comment by diamond0910** [comment]
抱歉，我们检查了这个bug。您只需要按以下命令更新一下JRender即可。

```
rm -r jrender
git clone https://github.com/Jittor/jrender.git
mv jrender jrender-bak
mv jrender-bak/jrender .
```

**Comment by zhenhao-huang** [comment]
好的，谢谢
